import os
import os.path
import sys
sys.path += ["../../build"]
import global_config
from   global_config import LIBUTIL
from   global_config import LIBCONFIG
from   global_config import get_targets
from   global_config import add_program

package      = "config"
lib_path     = "../lib"
include_path = "../include"
bin_path     = "../bin"  

conf = global_config.get_conf(os.getcwd() , package , 2)
env  = Environment()
conf.update_env( env , [LIBCONFIG , LIBUTIL] , ext_liblist = ["m","z","pthread"] , link = True)


add_program(env , conf , bin_path , "config_test" , "config_test.c")
add_program(env , conf , bin_path , "conf_test"   , "conf_test.c"  )

(local ) = get_targets( env , conf )
Default( local )
