import os
import os.path
import sys
sys.path += ["../../build"]
import global_config
from   global_config import LIBUTIL
from   global_config import LIBCONFIG


SDP_ROOT = ARGUMENTS.get('SDP_ROOT','/d/proj/bg/enkf')
if not os.path.exists( SDP_ROOT ):
   SDP_ROOT = None

conf = global_config.get_conf(SDP_ROOT , os.getcwd() , 2)
env  = Environment()
conf.update_env( env , [LIBCONFIG , LIBUTIL] , ext_liblist = ["m","z","pthread"] , link = True)

##################################################################



def add_program(env , conf , target , src , SDP_INSTALL = False):
    P = env.Program( target , src )
    env.InstallProgram( "../bin" , P)
    if conf.SDP_BIN:
        if SDP_INSTALL:
            env.InstallProgram(conf.SDP_BIN , P)




add_program(env , conf , "config_test" , "config_test.c" , False)
add_program(env , conf , "conf_test"   , "conf_test.c"   , False)

##################################################################
install = env.Alias('install',"../bin")
if SDP_ROOT:
   env.Alias('SDP_INSTALL' , conf.SDP_BIN)

Default( install )
