"""Merge blob and rdb

Revision ID: 2f8c7fe1481f
Revises: 14eca8adc993
Create Date: 2020-11-13 15:14:59.922505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from ert_shared.storage import ERT_STORAGE
from ert_shared.storage.entities_model import Observation
from ert_shared.storage.blobs_model import ErtBlob


# revision identifiers, used by Alembic.
revision = "2f8c7fe1481f"
down_revision = "14eca8adc993"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "observation", sa.Column("data_indexes", sa.PickleType(), nullable=True)
    )
    op.add_column(
        "observation", sa.Column("key_indexes", sa.PickleType(), nullable=True)
    )
    op.add_column("observation", sa.Column("stds", sa.PickleType(), nullable=True))
    op.add_column("observation", sa.Column("values", sa.PickleType(), nullable=True))
    op.add_column(
        "observation_response_definition_link",
        sa.Column("active", sa.PickleType(), nullable=True),
    )
    op.add_column("parameter", sa.Column("value", sa.PickleType(), nullable=True))
    op.add_column("response", sa.Column("values", sa.PickleType(), nullable=True))
    op.add_column(
        "response_definition", sa.Column("indexes", sa.PickleType(), nullable=True)
    )
    # ### end Alembic commands ###

    blob_session = ERT_STORAGE.BlobSession()

    for observation in session.query(Observation):
        data_indexes_ref = observation.data_indexes_ref
        data_indexes = blob_session.query(ErtBlob).filter(
            ErtBlob.id == data_indexes_ref
        )
        observation.data_indexes = data_indexes.value

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("response_definition", "indexes")
    op.drop_column("response", "values")
    op.drop_column("parameter", "value")
    op.drop_column("observation_response_definition_link", "active")
    op.drop_column("observation", "values")
    op.drop_column("observation", "stds")
    op.drop_column("observation", "key_indexes")
    op.drop_column("observation", "data_indexes")
    # ### end Alembic commands ###
