#!/usr/bin/env python3
import random
import subprocess
import sys

job_dispatch_path = sys.argv[-2]
run_path = sys.argv[-1]

# Write a file with the runpaths to where the jobs are running and writing information
# we later need when providing statuses for the jobs through the mocked bjobs command
with open("job_paths", "a+") as jobs_file:
    jobs_file.write(f"{run_path}\n")

# Just a log for testpurposes showing what is thrown against the bsub command
with open("bsub_log", "a+") as f:
    f.write(f"{str(sys.argv)}\n")

# Assigning a "unique" job id for each submitted job and print. This is how LSF provide
# response to ERT with the ID of the job.
_id = str(random.randint(0, 10000000))
print(f"Job <{_id}> is submitted to default queue <normal>.")

# Launch job-dispatch
subprocess.Popen([job_dispatch_path, run_path])
