---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-actions:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    cooldown:
      default-days: 7

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    versioning-strategy: "lockfile-only"
    groups:
      all-deps:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-commit-hooks:
        patterns:
          - "*"
    cooldown:
      default-days: 7
