version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

sphinx:
  builder: html
  configuration: docs/ert/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
