version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

sphinx:
  builder: html
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - cmake
    - libblas-dev
    - liblapack-dev
