#!/usr/bin/env bash


# Note: This script runs the experiments in the workspace one after each other.
# It is mainly kept around for CI purposes...


set -e

# TODO: This is a hack because of the lack of blob records. Hence, we currently
# copy the datafile to the compute nodes and this environment variable makes
# the workspace transportable.
export SPE1_WORKSPACE_ROOT=$(pwd)

ert3 run evaluation
ert3 export evaluation

ert3 record load designed_field_properties experiments/doe/field_properties.json
ert3 record load designed_wells experiments/doe/wells.json
ert3 run doe
ert3 export doe

ert3 run sensitivity
ert3 export sensitivity
