#!/usr/bin/env bash


# Note: This script runs the experiments in the workspace one after each other.
# It is mainly kept around for CI purposes...


set -e

ert3 run evaluation
ert3 export evaluation

ert3 record load designed_field_properties resources/field_properties.json
ert3 run doe
ert3 export doe

ert3 record load spe1case2_template resources/SPE1CASE2.DATA.jinja2 --blob-record
ert3 run sensitivity
ert3 export sensitivity
