#!/usr/bin/env bash


# Note: This script runs the experiments in the workspace one after each other.
# It is mainly kept around for CI purposes...


set -e

ert3 run evaluation
ert3 export evaluation

# we will check that data contains the recordtree subrecords
grep "WOPT:PROD" experiments/evaluation/data.json >/dev/null
grep "WWPT:PROD" experiments/evaluation/data.json >/dev/null
grep "WGPT:PROD" experiments/evaluation/data.json >/dev/null
grep "WWIT:INJ" experiments/evaluation/data.json >/dev/null

ert3 record load designed_field_properties resources/field_properties.json
ert3 run doe
ert3 export doe

ert3 run sensitivity
ert3 export sensitivity
