from __future__ import annotations

import re
from pathlib import Path

from .theme import ColorScheme
from .tokens import palette

_HEADER = (
    "/* AUTO-GENERATED by ert.gui.theming.generate_qss — DO NOT EDIT BY HAND.\n"
    " * Edit the template (ert/gui/theming/theme.qss.in) for structure or\n"
    " * ert/gui/theming/tokens.py for colour/size values, then run:\n"
    " *   uv run python -m ert.gui.theming.generate_qss\n"
    " */\n"
)

_THEME_DIR = Path(__file__).parent
_TEMPLATE = _THEME_DIR / "theme.qss.in"
_THEMES_DIR = _THEME_DIR.parent / "resources" / "gui" / "themes"

# Matches a template variable reference such as ``@nav-hover-bg``.
_VARIABLE = re.compile(r"@([a-z0-9-]+)")

# Matches the template's leading authoring comment, stripped so only the
# generated header (``_HEADER``) appears in the compiled output.
_LEADING_COMMENT = re.compile(r"\A\s*/\*.*?\*/\s*", re.DOTALL)


def _load_template() -> str:
    raw = _TEMPLATE.read_text(encoding="utf-8")
    return _LEADING_COMMENT.sub("", raw)


def _substitute(template: str, values: dict[str, str]) -> str:
    """Replace every ``@variable`` in ``template`` with its value.

    Args:
        template: The raw ``theme.qss.in`` contents.
        values: The ``variable -> value`` map for one colour scheme.

    Returns:
        The template with all variables resolved to concrete QSS values.

    Raises:
        KeyError: If the template references a variable absent from ``values``.
    """

    def replace(match: re.Match[str]) -> str:
        name = match.group(1)
        if name not in values:
            raise KeyError(
                f"Template references undefined variable '@{name}'. "
                "Add it to ert.gui.theming.tokens.palette()."
            )
        return values[name]

    return _VARIABLE.sub(replace, template)


def build_qss(color_scheme: ColorScheme, template: str | None = None) -> str:
    """Compile the template into the full stylesheet for ``color_scheme``."""
    source = _load_template() if template is None else template
    return _HEADER + "\n" + _substitute(source, palette(color_scheme))


def write_all(themes_dir: Path = _THEMES_DIR) -> list[Path]:
    """Compile and write ``light.qss`` and ``dark.qss`` from the template.

    Returns:
        The paths that were written.
    """
    template = _load_template()
    written: list[Path] = []
    for scheme in ColorScheme:
        path = themes_dir / f"{scheme.value}.qss"
        path.write_text(build_qss(scheme, template), encoding="utf-8")
        written.append(path)
    return written


if __name__ == "__main__":
    for written_path in write_all():
        print(f"wrote {written_path}")
