#!/usr/bin/env bash
set -e

ert3 run evaluation
ert3 status

ert3 clean evaluation
ert3 status

ert3 run evaluation
ert3 run uniform_evaluation
ert3 status

ert3 clean --all
ert3 status
ert3 run evaluation
ert3 export evaluation
ert3 run uniform_evaluation
ert3 export uniform_evaluation
ert3 status

ert3 record load designed_coefficients data/coefficients_record_doe.json
ert3 run doe
ert3 export doe

ert3 record load designed_coefficients_3 data/coefficients_record_doe3.json
ert3 run --local-test-run --realization 1 doe3
grep '"a": 1' local-test-run-*/coefficients.json

ert3 run sensitivity
ert3 export sensitivity

ert3 run uniform_sensitivity
ert3 export uniform_sensitivity

ert3 run fast_sensitivity
ert3 export fast_sensitivity

ert3 record load coefficients data/storage_coefficients.json
ert3 run partial_sensitivity
ert3 export partial_sensitivity

ert3 run x_uncertainty
ert3 export x_uncertainty

ert3 run function_evaluation
ert3 export function_evaluation
