"""Add timestamps

Revision ID: 3c5211cc1441
Revises: 22487ba09fe3
Create Date: 2021-02-10 10:41:15.534094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5211cc1441'
down_revision = '22487ba09fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute_value', sa.Column('time_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('attribute_value', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('ensemble', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('misfit', sa.Column('time_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('misfit', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('observation', sa.Column('time_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('observation', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('observation_attribute', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('observation_attribute', sa.Column('time_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('observation_attribute', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('observation_response_definition_link', sa.Column('time_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('observation_response_definition_link', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('parameter', sa.Column('time_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('parameter', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('parameter_prior', sa.Column('time_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('parameter_prior', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('time_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('project', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('response', sa.Column('time_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('response', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('response_definition', sa.Column('time_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('response_definition', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('update', sa.Column('time_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('update', sa.Column('time_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update', 'time_updated')
    op.drop_column('update', 'time_created')
    op.drop_column('response_definition', 'time_updated')
    op.drop_column('response_definition', 'time_created')
    op.drop_column('response', 'time_updated')
    op.drop_column('response', 'time_created')
    op.drop_column('project', 'time_updated')
    op.drop_column('project', 'time_created')
    op.drop_column('parameter_prior', 'time_updated')
    op.drop_column('parameter_prior', 'time_created')
    op.drop_column('parameter', 'time_updated')
    op.drop_column('parameter', 'time_created')
    op.drop_column('observation_response_definition_link', 'time_updated')
    op.drop_column('observation_response_definition_link', 'time_created')
    op.drop_column('observation_attribute', 'time_updated')
    op.drop_column('observation_attribute', 'time_created')
    op.drop_column('observation_attribute', 'id')
    op.drop_column('observation', 'time_updated')
    op.drop_column('observation', 'time_created')
    op.drop_column('misfit', 'time_updated')
    op.drop_column('misfit', 'time_created')
    op.drop_column('ensemble', 'time_updated')
    op.drop_column('attribute_value', 'time_updated')
    op.drop_column('attribute_value', 'time_created')
    # ### end Alembic commands ###
