PROD1:
  1:
    phase:
      value: OIL
    duration:
      value: 50
PROD2:
  1:
    phase:
      value: OIL
    duration:
      value: 50
PROD3:
  1:
    phase:
      value: OIL
    duration:
      value: 50
PROD4:
  1:
    phase:
      value: OIL
    duration:
      value: 50
INJECT1:
  1:
    phase:
      value: WATER
    duration:
      value: 50
INJECT2:
  1:
    phase:
      value: WATER
    duration:
      value: 50
INJECT3:
  1:
    phase:
      value: WATER
    duration:
      value: 50
INJECT4:
  1:
    phase:
      value: WATER
    duration:
      value: 50
INJECT5:
  1:
    phase:
      value: WATER
    duration:
      value: 50
INJECT6:
  1:
    phase:
      value: WATER
    duration:
      value: 50
INJECT7:
  1:
    phase:
      value: WATER
    duration:
      value: 50
INJECT8:
  1:
    phase:
      value: WATER
    duration:
      value: 50
