name: 🐛 Bug Report
description: File a bug report to help us improve
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? (You can include a screenshot if it helps explain)
      description: |
        Thanks for reporting a bug! Tell us what happened, what went wrong.
    validations:
      required: true

  - type: textarea
    id: what-did-you-expect-to-happen
    attributes:
      label: What did you expect to happen?
      description: Describe what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Detailed desription of how to reproduce the failure.
      render: console
    validations:
      required: false

  - type: checkboxes
    id: environment-checkboxes
    attributes:
      label: Environment where bug has been observed
      description: |
        Please check of the environments where this behavior has been observed.
      options:
        - label: Python 3.11
        - label: Python 3.12
        - label: macOS
        - label: RHEL8
        - label: RHEL9
        - label: Local queue
        - label: LSF queue
        - label: Slurm queue
        - label: OpenPBS queue
