import os
import os.path
import sys
sys.path += ["../../build"]
import global_config
from   global_config import LIBUTIL
from   global_config import LIBECL
from   global_config import LIBRMS

SDP_ROOT = ARGUMENTS.get('SDP_ROOT','/d/proj/bg/enkf')
conf = global_config.get_conf(SDP_ROOT , os.getcwd() , 2)
env  = Environment()

conf.update_env( env , [ LIBRMS , LIBECL , LIBUTIL ] ,  ext_liblist = ["m" , "z" , "pthread"] , link = True)

##################################################################



def add_program(env , conf , target , src , SDP_INSTALL = False):
    P = env.Program( target , src)
    env.Install( "../bin" , P)
    if conf.SDP_BIN:
        if SDP_INSTALL:
            env.Install(conf.SDP_BIN , P)


add_program(env , conf ,  "rms_extract" , "rms_extract.c" , False)
add_program(env , conf ,  "rms_setname" , "rms_setname.c" , False)
add_program(env , conf ,  "rms_stat"    , "rms_stat.c"    , False)
add_program(env , conf ,  "rms_test"    , "rms_test.c"    , False)
add_program(env , conf ,  "tag_list"    , "tag_list.c"    , False)

 
install = env.Alias('install',"../bin")
if SDP_ROOT:
   env.Alias('SDP_INSTALL' , conf.SDP_BIN)

Default( install )


