name: install_dependencies_scikit_sparse
description: Installs dependencies for scikit sparse

inputs:
  os:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsuitesparse-dev
        sudo dpkg -L libsuitesparse-dev | grep -E "include|lib"

        sudo apt-get install libeigen3-dev
      shell: bash
