import os
import os.path
import sys
sys.path += ["../../build"]
import global_config
from   global_config import LIBUTIL
from   global_config import LIBECL
from   global_config import LIBSCHED
from   global_config import add_program

SConscript(["perturb_history/SConstruct"])

conf = global_config.get_conf(os.getcwd() , 2)
env  = Environment()
conf.update_env( env , [LIBSCHED , LIBECL , LIBUTIL] , ["m","z","pthread"] , link = True)

##################################################################

bin_path = "../bin"
add_program(env , conf , bin_path , "sched_summary.x"         , "sched_summary.c")
add_program(env , conf , bin_path , "sched_test.x"            , "sched_test.c")
add_program(env , conf , bin_path , "update_ir.x"             , "update_ir.c")

##################################################################


install = env.Alias('install',bin_path)

env.Alias('SDP_INSTALL' , [bin_path , conf.SDP_BIN])

Default( install )


