version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - git fetch --unshallow --tags || true

python:
  install:
    - requirements: docs/everest/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dev
        - everest

sphinx:
  builder: html
  configuration: docs/everest/conf.py

formats:
  - pdf
  - epub
