import os
import os.path
import sys
sys.path += ["../../build"]
import global_config
from   global_config import LIBUTIL
from   global_config import LIBECL
from   global_config import add_static_library
from   global_config import add_header
from   global_config import get_targets

package      = "rms"
lib_path     = "../lib"
include_path = "../include"
bin_path     = "../bin"  

conf = global_config.get_conf(os.getcwd() , package , 2)
env  = Environment()
conf.update_env( env , [ LIBECL , LIBUTIL ] , link = False)

src_list    = Split("rms_file.c rms_util.c rms_tag.c rms_type.c rms_tagkey.c rms_stats.c rms_export.c")
header_list = Split("rms_file.h rms_util.h rms_tag.h rms_type.h rms_tagkey.h rms_stats.h rms_export.h")

add_static_library( env , conf , lib_path , package , src_list)
add_header( env , conf , include_path , header_list )

(local , SDP_INSTALL) = get_targets( env , conf )
Default( local )

