#!/usr/bin/env python
import sys
from res.fm.shell import move_file


if __name__ == "__main__":
    src = sys.argv[1]
    target = sys.argv[2]
    try:
        move_file(src, target)
    except IOError as e:
        sys.exit(f"MOVE_FILE failed with the following error: {e}")
