#!/usr/bin/env python
import sys
from ert_statoil import Shell


if __name__ == "__main__":
    src_path = sys.argv[1]
    target_path = sys.argv[2]

    Shell.copyDirectory( src_path , target_path )
