#!/usr/bin/env python
import sys
from ert_statoil import Shell

def symlink(target , link_name):
    Shell.symlink( target , link_name )


if __name__ == "__main__":
    target = sys.argv[1]
    link_name = sys.argv[2]
    symlink( target , link_name )
