#!/usr/bin/env python
"""Generates mock output files with data taken from fmu-sim2seis drogon test setup.

Generates only files needed for ERT integration:
 - synthetic seismic CSV modelled data files.
"""

import argparse
from pathlib import Path

import pandas as pd
from mock_sim2seis_common import (
    Attribute,
    BaseDate,
    Calculation,
    HorizonName,
    MonitorDate,
    StackingOffset,
    VerticalDomain,
    build_stem,
    generate_combos,
)


def generate_response(
    input_dir: Path,
    output_dir: Path,
    file_number: int,
    horizon: HorizonName,
    attribute: Attribute,
    stacking_offset: StackingOffset,
    calculation: Calculation,
    vertical_domain: VerticalDomain,
    base: BaseDate,
    monitor: MonitorDate,
) -> Path:
    """Return the path to a single seismic CSV file with drogon-like data."""
    stem = build_stem(
        horizon, attribute, stacking_offset, calculation, vertical_domain, base, monitor
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    filepath = output_dir / f"{stem}.csv"
    drogon_file = input_dir / f"{calculation.value}{file_number}.csv"

    df = pd.read_csv(drogon_file)
    df.to_csv(filepath, index=False)
    print(f"Written: {filepath}")
    return filepath


if __name__ == "__main__":
    """Return .csv responses generated by fmu-sim2seis.

    Output filenames correspond to observations:
    topvolantis--amplitude_full_mean_depth--20190701_20180101.csv
    topvolantis--amplitude_full_min_depth--20190701_20180101.csv

    Note that returned response data itself is not the same as fmu-sim2seis would return
    as output files from different dates (20180701_20180101, 20190701_20180101,
    20200701_20180101) were used as different realizations (0, 1, 2) for the same date
    20190701_20180101.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config_dir",
        type=Path,
        help="Directory containing configuration files.",
        required=True,
    )
    parser.add_argument(
        "--iter",
        type=int,
        help="Current iteration number.",
        required=True,
    )
    parser.add_argument(
        "--iens",
        type=int,
        help="Current realization number.",
        required=True,
    )

    args = parser.parse_args()
    file_number = (args.iens + args.iter) % 3
    input_dir = Path(args.config_dir / "drogon/fake-realization-responses")
    output_dir = Path("share/results/tables")

    combos = generate_combos(
        horizons=[HorizonName.TOPVOLANTIS],
        bases=[BaseDate.JAN2018],
        monitors=[MonitorDate.JUL2019],
        calculations=[Calculation.MIN, Calculation.MEAN],
    )
    for combo in combos:
        generate_response(
            input_dir,
            output_dir,
            file_number,
            *combo,
        )
