import os
import os.path
import sys
sys.path += ["../../../build"]
import global_config
from   global_config import LIBUTIL
from   global_config import LIBECL
from   global_config import LIBSCHED
from   global_config import LIBCONFIG
from   global_config import add_program

env  = Environment()
conf = global_config.get_conf(os.getcwd() , 3)
conf.update_env( env , [LIBSCHED , LIBECL , LIBCONFIG , LIBUTIL] , ["m","z","pthread"] , link = True)



bin_path = "../../bin"

add_program(env , conf , bin_path , "perturb_history" ,["perturb_history.c" , "well_rate.c" , "group_rate.c" , "pert_util.c"])

install = env.Alias('install',bin_path)
env.Alias('SDP_INSTALL' , [bin_path , conf.SDP_BIN])

Default( install )


