#!/usr/bin/env python
import sys
from res.fm.shell import copy_directory


if __name__ == "__main__":
    src_path = sys.argv[1]
    target_path = sys.argv[2]

    copy_directory(src_path, target_path)
