#!/usr/bin/env python
import sys
from res.fm.shell import mkdir


if __name__ == "__main__":
    path = sys.argv[1]
    try:
        mkdir(path)
    except IOError as e:
        sys.exit(f"MAKE_DIRECTORY failed with the following error: {e}")
