#!/usr/bin/env python
import sys
from res.fm.shell import delete_file


if __name__ == "__main__":
    try:
        for file in sys.argv[1:]:
            delete_file(file)
    except IOError as e:
        sys.exit(f"DELETE_FILE failed with the following error: {e}")
