#!/usr/bin/env python
import sys
from res.fm.shell import symlink


if __name__ == "__main__":
    target = sys.argv[1]
    link_name = sys.argv[2]
    try:
        symlink(target, link_name)
    except IOError as e:
        sys.exit(f"SYMLINK failed with the following error: {e}")
