import os
import os.path
import sys
sys.path += ["../../build"]
import global_config
from   global_config import LIBUTIL
from   global_config import LIBCONFIG
from   global_config import LIBJOB_QUEUE
from   global_config import add_program
from   global_config import get_targets

package      = "job_queue"
lib_path     = "../lib"
include_path = "../include"
bin_path     = "../bin"  


conf = global_config.get_conf(os.getcwd() , package , 2)
env  = Environment()
conf.update_env( env , [LIBJOB_QUEUE , LIBCONFIG , LIBUTIL] , [ "bat"  ,"lsf" , "nsl" , "z" , "m" , "pthread"] , link = True )

add_program(env , conf , bin_path , "block_node"         , "block_node.c" )
(local , SDP_INSTALL) = get_targets( env , conf )
Default( local )


