import os
import os.path
import sys
sys.path += ["../../build"]
import global_config
from   global_config import LIBUTIL
from   global_config import LIBJOB_QUEUE
from   global_config import EXTERNAL

conf = global_config.get_conf(os.getcwd() , 2)
env  = Environment()
conf.update_env( env , [LIBUTIL , LIBJOB_QUEUE , EXTERNAL] , ["bat"  ,"lsf" , "nsl" , "m" , "z" , "pthread"] , link = True)

##################################################################



def add_program(env , conf , target , src , SDP_INSTALL = False):
    P = env.Program( target , src )
    env.Install( "../bin" , P)
    if SDP_INSTALL:
        env.Install(conf.SDP_BIN , P)




add_program(env , conf , "block_node"         , "block_node.c"   , True)

##################################################################

if not os.path.exists( conf.SDP_BIN ):
    os.makedirs( conf.SDP_BIN )
 
install = env.Alias('install',"../bin")
env.Alias('SDP_INSTALL' , conf.SDP_BIN)

Default( install )


