import os
import os.path
import sys
sys.path += ["../../build"]
import global_config
from   global_config import LIBUTIL
from   global_config import LIBJOB_QUEUE
from   global_config import EXTERNAL

SDP_ROOT = ARGUMENTS.get('SDP_ROOT','/d/proj/bg/enkf')
conf = global_config.get_conf(SDP_ROOT , os.getcwd() , 2)
env  = Environment()
conf.update_env( env , [LIBUTIL , LIBJOB_QUEUE , EXTERNAL] , ["bat"  ,"lsf" , "nsl" , "m" , "z" , "pthread"] , link = True)

##################################################################



def add_program(env , conf , target , src , SDP_INSTALL = False):
    P = env.Program( target , src )
    env.Install( "../bin" , P)
    if conf.SDP_BIN:
        if SDP_INSTALL:
            env.Install(conf.SDP_BIN , P)




add_program(env , conf , "block_node"         , "block_node.c"   , True)

##################################################################

 
install = env.Alias('install',"../bin")
if SDP_ROOT:
   env.Alias('SDP_INSTALL' , conf.SDP_BIN)

Default( install )


