from typing import Final

COLOR_QUEUED: Final = (183, 191, 199)
COLOR_FAILED: Final = (207, 34, 46)
COLOR_FINISHED: Final = (45, 164, 78)
COLOR_PENDING: Final = COLOR_QUEUED
COLOR_RUNNING: Final = (214, 178, 42)
COLOR_UNKNOWN: Final = (140, 149, 159)
COLOR_WAITING: Final = COLOR_QUEUED
COLOR_CANCELLED: Final = (234, 238, 242)
COLOR_WARNING: Final = (255, 103, 0)

ENSEMBLE_STATE_CANCELLED: Final = "Cancelled"
ENSEMBLE_STATE_FAILED: Final = "Failed"
ENSEMBLE_STATE_STARTED: Final = "Starting"
ENSEMBLE_STATE_STOPPED: Final = "Stopped"
ENSEMBLE_STATE_UNKNOWN: Final = "Unknown"

FORWARD_MODEL_STATE_FAILURE: Final = "Failed"
FORWARD_MODEL_STATE_FINISHED: Final = "Finished"
FORWARD_MODEL_STATE_INIT: Final = "Pending"
FORWARD_MODEL_STATE_RUNNING: Final = "Running"
FORWARD_MODEL_STATE_START: Final = "Running"
FORWARD_MODEL_STATE_CANCELLED: Final = "Cancelled"

REALIZATION_STATE_FAILED: Final = "Failed"
REALIZATION_STATE_FINISHED: Final = "Finished"
REALIZATION_STATE_PENDING: Final = "Pending"
REALIZATION_STATE_RUNNING: Final = "Running"
REALIZATION_STATE_UNKNOWN: Final = "Unknown"
REALIZATION_STATE_WAITING: Final = "Waiting"

REAL_STATE_TO_COLOR: Final = {
    REALIZATION_STATE_UNKNOWN: COLOR_UNKNOWN,
    REALIZATION_STATE_FINISHED: COLOR_FINISHED,
    REALIZATION_STATE_FAILED: COLOR_FAILED,
    REALIZATION_STATE_RUNNING: COLOR_RUNNING,
    REALIZATION_STATE_PENDING: COLOR_PENDING,
    REALIZATION_STATE_WAITING: COLOR_WAITING,
}
