from typing import Final

COLOR_FAILED: Final = (255, 200, 200)
COLOR_FINISHED: Final = (127, 201, 127)
COLOR_PENDING: Final = (190, 174, 212)
COLOR_RUNNING: Final = (255, 255, 153)
COLOR_UNKNOWN: Final = (128, 128, 128)
COLOR_WAITING: Final = (164, 200, 255)

ENSEMBLE_STATE_CANCELLED: Final = "Cancelled"
ENSEMBLE_STATE_FAILED: Final = "Failed"
ENSEMBLE_STATE_STARTED: Final = "Starting"
ENSEMBLE_STATE_STOPPED: Final = "Stopped"
ENSEMBLE_STATE_UNKNOWN: Final = "Unknown"

FORWARD_MODEL_STATE_FAILURE: Final = "Failed"
FORWARD_MODEL_STATE_FINISHED: Final = "Finished"
FORWARD_MODEL_STATE_INIT: Final = "Pending"
FORWARD_MODEL_STATE_RUNNING: Final = "Running"
FORWARD_MODEL_STATE_START: Final = "Running"

REALIZATION_STATE_FAILED: Final = "Failed"
REALIZATION_STATE_FINISHED: Final = "Finished"
REALIZATION_STATE_PENDING: Final = "Pending"
REALIZATION_STATE_RUNNING: Final = "Running"
REALIZATION_STATE_UNKNOWN: Final = "Unknown"
REALIZATION_STATE_WAITING: Final = "Waiting"

REAL_STATE_TO_COLOR: Final = {
    REALIZATION_STATE_UNKNOWN: COLOR_UNKNOWN,
    REALIZATION_STATE_FINISHED: COLOR_FINISHED,
    REALIZATION_STATE_FAILED: COLOR_FAILED,
    REALIZATION_STATE_RUNNING: COLOR_RUNNING,
    REALIZATION_STATE_PENDING: COLOR_PENDING,
    REALIZATION_STATE_WAITING: COLOR_WAITING,
}
