"""Initial state

Revision ID: a360248166fd
Revises: 60c97768cf67
Create Date: 2020-10-23 08:49:35.327386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a360248166fd"
down_revision = "60c97768cf67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ert_blob",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.PickleType(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ert_blob")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ert_blob")
    # ### end Alembic commands ###
