-
  name: field_properties
  type: stochastic
  distribution:
    type: uniform
    input:
      lower_bound: 0.1
      upper_bound: 0.9
  variables: ["porosity", "x_mid_permability"]
-
  name: wells_no_delay
  type: stochastic
  distribution:
    type: uniform
    input:
      lower_bound: 1
      upper_bound: 1
  variables: ["delay"]
-
  name: wells
  type: stochastic
  distribution:
    type: uniform
    input:
      lower_bound: 1
      upper_bound: 365
  variables: ["delay"]
