#define SPLASH_LENGTH 9
const char *splash_text[SPLASH_LENGTH] = {
"iiLLGGGGjj  ,,              ,,              tt,,;;,,::jj    ,,jj                ;;,,                ",
"GGLL,,,,,,,,jj      ....  ::LL..    ....    ii,,jjtt,,GG    ,,LL              ..jjtt    ..    ....  ",
"GGjj::    ,,GGGG::LLGGGGtt,,GGGG,,jjGGGGLL  jjttjjtt,,GG::::ttLLttLL  ,,GG,,GGGGGGttttGGGG,,LLGGGGtt",
"ttLLGGGG,,,,jj    ::,,ttLL,,LL..  GG::  GG::jjttjjtt,,GGGGGGGGLL..GG..jjjjjjjj  jjttttLL  ,,GG  ::GG",
"      ttLL,,jj    GGjjjjLL,,LL....GG..  GG,,jjttjjtt,,GG    ,,LL  jjttGG,,jjtt  jjttttLL  ,,LL  ::GG",
",,,,,,ffLL,,LL,,::GG,,ttLL,,GG,,..GGii,,GG..jjttjjtt,,GG    ,,LL  ,,GGjj  ttLL,,jjttttLL  ::GG,,ttGG",
"ttffLLjj::..jjLL::ttLLfftt  jjLL,,,,ffLL,,  ;;,,,,tt,,jj    ,,jj  ..GG,,  ..jjLLjj,,,,jj    ;;LLjj,,",
"                                                                  ;;LL                              ",
"                                                                  jjjj                              "};
