ENSEMBLE_SMOOTHER_MODE = "ensemble_smoother"
ENSEMBLE_EXPERIMENT_MODE = "ensemble_experiment"
ITERATIVE_ENSEMBLE_SMOOTHER_MODE = "iterative_ensemble_smoother"
ES_MDA_MODE = "es_mda"
TEST_RUN_MODE = "test_run"
WORKFLOW_MODE = "workflow"
