#!/usr/bin/env python3
import os
import sys
from pathlib import Path
from shutil import which

SOURCE_ROOT = Path(__file__).parent.parent


def find_build_dir() -> Path:
    for path in (SOURCE_ROOT / "_skbuild").glob("**/build.ninja"):
        return path.parent

    sys.exit("_skbuild build directory not found. Did you run 'script/build'?")


def main():
    ctest = which("ctest")

    if ctest is None:
        sys.exit("'ctest' executable not found")

    if len(sys.argv) > 1:
        args = sys.argv[1:]
    else:
        args = ["--output-on-failure"]

    os.chdir(find_build_dir())
    os.execve(
        ctest,
        [ctest, *args],
        env={
            **os.environ,
            "ERT_SHOW_BACKTRACE": "1",
        },
    )


if __name__ == "__main__":
    main()
