#!/usr/bin/env bash
set -e

ert3 init

ert3 run evaluation
ert3 export evaluation

ert3 run uniform_evaluation
ert3 export uniform_evaluation

ert3 record load designed_coefficients experiments/doe/coefficients_record.json
ert3 run doe
ert3 export doe

ert3 run sensitivity
ert3 export sensitivity

ert3 run uniform_sensitivity
ert3 export uniform_sensitivity
