import os
import os.path
import sys
sys.path += ["../../build"]
import global_config
from   global_config import LIBUTIL

conf = global_config.get_conf(os.getcwd() , 2)
env  = Environment()
conf.update_env( env , [ LIBUTIL ] , link = False)

src_list    = Split("config.c conf.c conf_util.c conf_data.c")
header_list = Split("config.h conf.h conf_data.h")


LIB = env.StaticLibrary("config" , src_list)
env.Install("../lib" , LIB)
env.Install(conf.SDP_LIB , LIB )

env.Install("../include" , header_list)
env.Install(conf.SDP_LIB , header_list)

##################################################################

if not os.path.exists( conf.SDP_LIB ):
    os.makedirs( conf.SDP_LIB )
 
install     = env.Alias('install',["../lib" , "../include"])
SDP_INSTALL = env.Alias('SDP_INSTALL' , [conf.SDP_LIB , conf.SDP_INCLUDE])

Default( install )
