import os
import os.path
import sys
sys.path += ["../../build"]
import global_config
from   global_config import LIBUTIL

SDP_ROOT = ARGUMENTS.get('SDP_ROOT','/d/proj/bg/enkf')
if not os.path.exists( SDP_ROOT ):
   SDP_ROOT = None

conf = global_config.get_conf(SDP_ROOT , os.getcwd() , 2)
env  = Environment()
conf.update_env( env , [ LIBUTIL ] , link = False)

src_list    = Split("config.c conf.c conf_util.c conf_data.c")
header_list = Split("config.h conf.h conf_data.h")


LIB = env.StaticLibrary("config" , src_list)
env.InstallLibrary("../lib" , LIB)
env.InstallHeader("../include" , header_list)


##################################################################

 
install = env.Alias('install',["../lib" , "../include"])
if SDP_ROOT:
   env.InstallHeader(conf.SDP_LIB , header_list)
   env.InstallLibrary(conf.SDP_LIB , LIB )
   SDP_INSTALL = env.Alias('SDP_INSTALL' , [conf.SDP_LIB , conf.SDP_INCLUDE])

Default( install )
