
FM_JOB_ID = "id"
FM_JOB_TYPE = "type"
FM_JOB_INPUTS = "inputs"

TERMINATE = "terminate"
PAUSE = "pause"
ACTION = "action"
TERMINATED = "terminated"
DONE = "done"
STATUS = "status"
FORWARD_MODELS = "forward_models"
REALIZATIONS = "realizations"
EVENT_INDEX = "event_index"
CREATED = "created"

REALIZATION_STATUS = "status"
REALIZATION_FORWARD_MODELS = "forward_models"

EVTYPE_FM_JOB_START = "com.equinor.ert.forward_model_job.start"
EVTYPE_FM_JOB_RUNNING = "com.equinor.ert.forward_model_job.running"
EVTYPE_FM_JOB_SUCCESS = "com.equinor.ert.forward_model_job.success"
EVTYPE_FM_JOB_FAILURE = "com.equinor.ert.forward_model_job.failure"

EVTYPE_FM_STEP_START = "com.equinor.ert.forward_model_step.start"
EVTYPE_FM_STEP_FAILURE = "com.equinor.ert.forward_model_step.failure"
EVTYPE_FM_STEP_SUCCESS = "com.equinor.ert.forward_model_step.success"

FM_JOB_ATTR_NAME = "name"
FM_JOB_ATTR_EXECUTABLE = "executable"
FM_JOB_ATTR_TARGET_FILE = "target_file"
FM_JOB_ATTR_ERROR_FILE = "error_file"
FM_JOB_ATTR_START_FILE = "start_file"
FM_JOB_ATTR_STDOUT = "stdout"
FM_JOB_ATTR_STDERR = "stderr"
FM_JOB_ATTR_STDIN = "stdin"
FM_JOB_ATTR_ARGLIST = "argList"
FM_JOB_ATTR_ENVIRONMENT = "environment"
FM_JOB_ATTR_EXEC_ENV = "exec_env"
FM_JOB_ATTR_LICENSE_PATH = "license_path"
FM_JOB_ATTR_MAX_RUNNING_MINUTES = "max_running_minutes"
FM_JOB_ATTR_MAX_RUNNING = "max_running"
FM_JOB_ATTR_MIN_ARG = "min_arg"
FM_JOB_ATTR_ARG_TYPES = "arg_types"
FM_JOB_ATTR_MAX_ARG = "max_arg"
