"""Add size to ensemble

Revision ID: 73541c7b7aa6
Revises: 79137bad215d
Create Date: 2021-04-27 14:18:53.641564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73541c7b7aa6"
down_revision = "c96ec073f9ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ensemble", sa.Column("size", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ensemble", "size")
    # ### end Alembic commands ###
