"""Add realization_index to record

Revision ID: 98601344bcf5
Revises: 65569f4f3756
Create Date: 2021-02-24 14:53:07.632942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "98601344bcf5"
down_revision = "65569f4f3756"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("record", sa.Column("realization_index", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("record", "realization_index")
    # ### end Alembic commands ###
