"""Add record unique constraint

Revision ID: fc7aef9b17f8
Revises: 4effed76d1e2
Create Date: 2021-02-24 17:05:51.046173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fc7aef9b17f8"
down_revision = "4effed76d1e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "record", ["ensemble_id", "realization_index", "name"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "record", type_="unique")
    # ### end Alembic commands ###
