#!/usr/bin/env python
import sys
import json

# This forward model job is quite funny, and hardcodes significant
# interaction with the the EXT_PARAM and GEN_DATA nodes added in the
# test_everest.py test.

order = json.load( open("WELL_ORDER.json"))
inj = json.load( open("WELL_INJECTION.json"))

with open("order_0","w") as f:
    for key in ["W1","W2","W3"]:
        f.write("%g\n" % order[key])

with open("injection_0","w") as f:
    for key in ["W1","W4"]:
        f.write("%g\n" % inj[key])

