BLUE_BACKGROUND = "#d5eaf4"
BLUE_TEXT = "#045e8d"
RED_BACKGROUND = "#ffd2d1"
RED_TEXT = "#90042c"
YELLOW_BACKGROUND = "#ffe7d6"
YELLOW_TEXT = "#7f4600"

__all__ = [
    "BLUE_BACKGROUND",
    "BLUE_TEXT",
    "RED_BACKGROUND",
    "RED_TEXT",
    "YELLOW_BACKGROUND",
    "YELLOW_TEXT",
]
