#!/usr/bin/env python
import sys, os
from res.fm.shell import careful_copy_file

if __name__ == "__main__":
    src = sys.argv[1]
    if len(sys.argv) > 2:
        target = sys.argv[2]
        careful_copy_file(src, target)
    else:
        careful_copy_file(src)
