WCONPROD
 WELL-1 SHUT BHP 5* 100 /
 WELL-2 SHUT BHP 5* 100 /
 WELL-3 SHUT BHP 5* 100 /
 WELL-4 SHUT BHP 5* 100 /
 WELL-5 SHUT BHP 5* 100 /
/

-- MODIFIED by schmerge forward model

DATES
 1 JAN 2022 /
/

DATES
 01 JUN 2022 / --ADDED
/

--start templates/welopen.jinja

WELOPEN
  'WELL-1' 'OPEN' /
/

--end templates/welopen.jinja

--start templates/welshut.jinja

WELOPEN
  'WELL-2' 'SHUT' /
/

--end templates/welshut.jinja

--start templates/welopen.jinja

WELOPEN
  'WELL-3' 'OPEN' /
/

--end templates/welopen.jinja

--start templates/welopen.jinja

WELOPEN
  'WELL-4' 'OPEN' /
/

--end templates/welopen.jinja

--start templates/welshut.jinja

WELOPEN
  'WELL-5' 'SHUT' /
/

--end templates/welshut.jinja

DATES
 1 JAN 2023 /
/

DATES
 06 FEB 2023 / --ADDED
/

--start templates/welshut.jinja

WELOPEN
  'WELL-1' 'SHUT' /
/

--end templates/welshut.jinja

--start templates/welopen.jinja

WELOPEN
  'WELL-2' 'OPEN' /
/

--end templates/welopen.jinja

--start templates/welshut.jinja

WELOPEN
  'WELL-3' 'SHUT' /
/

--end templates/welshut.jinja

--start templates/welopen.jinja

WELOPEN
  'WELL-4' 'OPEN' /
/

--end templates/welopen.jinja

--start templates/welshut.jinja

WELOPEN
  'WELL-5' 'SHUT' /
/

--end templates/welshut.jinja

DATES
 14 OCT 2023 / --ADDED
/

--start templates/welshut.jinja

WELOPEN
  'WELL-1' 'SHUT' /
/

--end templates/welshut.jinja

--start templates/welopen.jinja

WELOPEN
  'WELL-2' 'OPEN' /
/

--end templates/welopen.jinja

--start templates/welopen.jinja

WELOPEN
  'WELL-3' 'OPEN' /
/

--end templates/welopen.jinja

--start templates/welshut.jinja

WELOPEN
  'WELL-4' 'SHUT' /
/

--end templates/welshut.jinja

--start templates/welshut.jinja

WELOPEN
  'WELL-5' 'SHUT' /
/

--end templates/welshut.jinja

DATES
 1 JAN 2024 /
/

DATES
 20 JUN 2024 / --ADDED
/

--start templates/welshut.jinja

WELOPEN
  'WELL-1' 'SHUT' /
/

--end templates/welshut.jinja

--start templates/welshut.jinja

WELOPEN
  'WELL-2' 'SHUT' /
/

--end templates/welshut.jinja

--start templates/welshut.jinja

WELOPEN
  'WELL-3' 'SHUT' /
/

--end templates/welshut.jinja

--start templates/welopen.jinja

WELOPEN
  'WELL-4' 'OPEN' /
/

--end templates/welopen.jinja

--start templates/welshut.jinja

WELOPEN
  'WELL-5' 'SHUT' /
/

--end templates/welshut.jinja

DATES
 1 JAN 2025 /
/
