"""empty schema

Revision ID: 11d6bbf0a926
Revises: 
Create Date: 2020-11-19 10:07:26.718334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "11d6bbf0a926"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
