name: Run test-data

on:
 push:
   branches:
     - main
     - 'version-**'
 workflow_call:
 workflow_dispatch:

permissions:
   contents: read

env:
  ERT_SHOW_BACKTRACE: 1
  UV_FROZEN: true
  OMP_NUM_THREADS: 1

jobs:
  run-ert-test-data:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        filter: tree:0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
      with:
        enable-cache: true
        prune-cache: false
        python-version: ${{ matrix.python-version }}

    - name: Install ERT and dependencies
      run: |
        uv sync

    - name: Test poly example
      run: |
        pushd test-data/ert/poly_example
        uv run ert test_run poly.ert
        popd

    - name: Test snake_oil
      run: |
        pushd test-data/ert/snake_oil
        uv pip install oil_reservoir_synthesizer resdata
        uv run ert test_run snake_oil.ert
        popd

    - name: Test snake_oil_field
      run: |
        pushd test-data/ert/snake_oil_field
        uv run ert test_run snake_oil.ert
        popd
