name: Run pre-commit

on:
 push:
   branches:
     - main
     - 'version-**'
 workflow_call:

permissions:
   contents: read

env:
  UV_FROZEN: true

jobs:
  check-style:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        filter: tree:0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
      with:
        enable-cache: true
        prune-cache: false
        python-version: ${{ matrix.python-version }}

    - name: Install ERT with style dependencies
      run: |
        uv sync --group style

    - name: Download shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install shellcheck
    - name: Check testkomodo.sh
      run: shellcheck -s bash ci/testkomodo.sh
      shell: bash

    - uses: ./.github/actions/install_dependencies_qt
      with:
        os: ubuntu-latest

    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit
      if: ${{ always() }}
      run: |
        SKIP=no-commit-to-branch uv run pre-commit run --all-files --hook-stage pre-push --show-diff-on-failure
