on:
  workflow_dispatch:
  workflow_call:
    inputs:
      os:
        type: string
      python-version:
        type: string

permissions:
   contents: read

env:
  UV_FROZEN: true

jobs:
  test-screenshots:
    name: Run screenshot tests
    timeout-minutes: 20
    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - uses: ./.github/actions/install_dependencies_qt
      with:
        os: ${{ inputs.os }}

    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      id: setup_python
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        enable-cache: true
        prune-cache: false
        python-version: ${{ inputs.python-version }}

    - name: Install ert
      run: |
        uv sync --group dev

    - name: Run screenshot tests
      run: |
        uv run just screenshot-comparison-test

    - name: Pack updated screenshot in case of failure
      if: ${{ failure() }}
      run: |
        uv run just pack-updated-screenshots

    - name: Upload updated screenshot images from failed image comparison test
      id: upload-screenshot-images
      if: ${{ failure() }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      continue-on-error: true
      with:
        name: updated-screenshots-${{ github.run_number }}-${{ github.run_id }}-${{ inputs.python-version }}
        path: updated-screenshots

    - name: User instructions for fetching updated screenshots
      if: ${{ failure() && steps.upload-screenshot-images.outputs.artifact-id != '' }}
      run: |
        echo " * Ensure gh command line utility is installed"
        echo " * Do 'gh auth login' if you are not authenticated yet"
        echo "$ rm -rf .tmp; gh run download ${{ github.run_id }} -D .tmp -n updated-screenshots-${{ github.run_number }}-${{ github.run_id }}-${{ inputs.python-version }}; cp -a .tmp/* ."
        echo " * Then review your local changes and commit+squash them."
        echo ""
        echo "(This steps exits with a failure code in order to have its output highlighted in Github actions web interface)"
        exit 1
