name: Test EVEREST Models

# This job checks whether current main of everest-models
# is compatible with the changes. It is not required to pass
# before merging, but breakage should be followed by fix in everest-models

on:
 push:
   branches:
     - main
     - 'version-**'
 workflow_call:
 workflow_dispatch:

permissions:
   contents: read

env:
  UV_FROZEN: true
  OMP_NUM_THREADS: 1

jobs:
    test-everest-models:
        name: Test everest-models
        timeout-minutes: 10
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.12']
        steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
          with:
            fetch-depth: 0
            filter: tree:0

        - name: Install dependencies
          uses: ./.github/actions/install_dependencies_qt
          with:
            os: ubuntu-latest

        - name: Set up Python
          uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install uv
          uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
          with:
            enable-cache: true
            prune-cache: false
            python-version: ${{ matrix.python-version }}

        - name: Install ert
          run: |
            uv sync

        - name: Get everest-models
          run: |
            git clone https://github.com/equinor/everest-models.git

        - name: "Install and test everest-models"
          run: |
            pushd everest-models
            VIRTUAL_ENV=../.venv uv pip install ".[test]"
            UV_PROJECT_ENVIRONMENT=../.venv uv run --no-sync pytest -sv --hypothesis-profile ci --run-slow
